### ISSUE TITLE
JIPipe dependencies prevent from GUI startup after fresh install

### ISSUE THREAD

**Issue by abhamacher** [applied-systems-biology/jipipe#7] opened 2023-01-12 10:12 UTC
Hi all,

I was finally installing JIPipe this morning in Fiji but struggled with the installation, so would like to provide you some feedback on this to maybe improve the online documentation.

I was basically following your guide on the [website](https://www.jipipe.org/installation/), by downloading a fresh Fiji installation first, then adding the "JIPipe" update site. Installation went successful, but starting the GUI failed with the attached messages. 

![jipipe_startup](https://user-images.githubusercontent.com/61734239/212039597-13956a0e-b46b-46ef-8f51-c500f3eb3571.PNG)
[jpipe-gui_fiji_log.txt](https://github.com/applied-systems-biology/jipipe/files/10400455/jpipe-gui_fiji_log.txt)

The GUI is not showing up any further and therefore the needed dependencies cannot be installed as described [here](https://www.jipipe.org/installation/dependencies/). After adding the mentioned plugins (the 4 that can be seen on the [screenshot](https://www.jipipe.org/img/installation/missing_dependencies_new.png)) manually to the update site, the JIPipe GUI was started successfully. I'm not sure which of these plugins was preventing the GUI startup, but maybe you can add that plugin the installation notes. 

In addition, the clij2 plugin is throwing an error during each Fiji startup that something of the clij-package is missing. So, basically clij has to be installed as well.

Thanks for providing JIPipe, really looking forward to getting into it!
Anna

**Comment by rumangerst** [comment] 2023-01-12 11:08
Thank you for notifying me about this issue. Apparently some library was updated, which breaks some error logging function. 

I am currently uploading a new JIPipe version and will inform you when the issue is resolved.

**Comment by rumangerst** [comment] 2023-01-12 11:56
The main issue should now be resolved in JIPipe version 1.77.0. 

The CLIJ2 errors are as correctly identified by you caused by a missing CLIJ2 installation (maybe you clicked away the CLIJ2 installation options on activating the extension?). Either disable CLIJ2 in JIPipe via the extension manager (`Plugins > Manage JIPipe plugins`) or install the `clij` and `clij2` update sites. 

Please feel free to inform me if you have any more issues or questions!

**Closed as completed by rumangerst** 2023-01-12 11:56 UTC
